### ISSUE TITLE
How to initialize handyAttachments variable from an api? 

### ISSUE THREAD

**Issue by MalinaliRap** [alijahanpak/handy-uploader#12]
I get images from api that I build through laravel, my api returns the object equal to the object created by handyUploader, as an example below:

![image](https://user-images.githubusercontent.com/19911218/125664905-4c1a81a3-590b-489b-aae6-c9242a148e1e.png)

The images load, but when deleting, instead of deleting one image, delete all, can someone help me?

**Comment by alijahanpak** [comment]
Can you send images(array) from api for me?

**Comment by MalinaliRap** [comment]
![image](https://user-images.githubusercontent.com/19911218/125821488-832fa15b-4afa-4f8d-8d12-e6ddad311177.png)

**Comment by MalinaliRap** [comment]
![image](https://user-images.githubusercontent.com/19911218/125821541-16d5c5af-30fd-454f-8262-7961b78a84bc.png)

**Comment by MalinaliRap** [comment]
[
    {
        "name": "0g4qFwideK.jpeg",
        "base64": "",
	"size": 692026,
        "format": "image/jpeg;base64",
        "tags": [],
        "showDetailState": false,
        "src": ""
	"description": ""
    },
    {
        "name": "cMDAoLKOIF.jpeg",
        "base64": "",
	"size": 602858,
        "format": "image/jpeg;base64",
        "tags": [],
        "showDetailState": false,
        "src": ""
	"description": ""
    },
    {
        "name": "lrcFHLpVyE.jpeg",
        "base64": ""
	"size": 254263,
        "format": "image/jpeg;base64",
        "tags": [],
        "showDetailState": false,
        "src": ""
		"description": ""
    }
]

**Comment by MalinaliRap** [comment]
I removed the base64 attribute and the src attribute, because they were too long to send here

**Comment by alijahanpak** [comment]
Thanks @MalinaliRap . Solved this issue in handy-uploader 1.1.8
