### ISSUE TITLE
[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

### ISSUE THREAD

**Issue by keyhoffman** [alijahanpak/handy-uploader#2]
I am getting the following error: `[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.`

I think the error is coming from the line:` v-for="attachment in tempAttachmentChanged" :key="attachment"`

You are using the `attachment` object as a `key`. The `key` needs to be a string/number. Using `attachment.name` as the `key` will probably fix this

![image](https://user-images.githubusercontent.com/19439761/89067191-6a18ed00-d334-11ea-8288-dc94b6cc667e.png)

**Comment by keyhoffman** [comment]
There are two lines where this is happening in the file `handyUploader.vue`:

1. 353
2. 414

**Comment by alijahanpak** [comment]
Thank you @keyhoffman  for checking handy-uplader package. I fixed this issue in new release (1.1.0).
