### ISSUE TITLE
Rtl support on headers not working

### ISSUE THREAD

**Issue by idanmarko** [alijahanpak/handy-uploader#4]
After setting rtlSupport to true 
![image](https://user-images.githubusercontent.com/5197056/97836293-a6b60500-1ce4-11eb-9cc2-9161a964a8bc.png)

The outputs seem like this:
![image](https://user-images.githubusercontent.com/5197056/97836306-af0e4000-1ce4-11eb-954e-b4d486976ae4.png)

And the css of each th column contains "text-left" class wich sets "text-align: left !important"
![image](https://user-images.githubusercontent.com/5197056/97836325-b897a800-1ce4-11eb-88b1-ede3f971c322.png)

**Comment by alijahanpak** [comment]
Thank you @idanmarko  for checking handy-uplader package. I fixed this issue in new release (1.1.4). Now you can use rtl suppurt for table header
