### ISSUE TITLE
Issue uploading files to server using axios

### ISSUE THREAD

**Issue by okaoui** [alijahanpak/handy-uploader#5]
Please can you provide a code example to upload files to server

**Comment by alijahanpak** [comment]
it's depend on your strategy for upload data on server. [handy-uploader](https://friendly-varahamihira-45c09f.netlify.app/documentation/) return Base64 for every selected file in Array and 'file' object, and you can use format property (Base64) to upload files on server. 
sample of returned array : 

```javascript
[
    { 
        file: {
            name: 'file name',
            size: 'file size',
            base64: 'base64', 
            format: 'file upload format. for example:image/jpeg;base64',
            tags: [],
            description: 'file description'
        }
    }
 ]```

**Comment by okaoui** [comment]
Thanks for reply.
To be clear here is my service upload function which accept a file parameter but how to convert base64 to file and also for information my backend service accept multipart form data. 
upload(file) {
      let formData = new FormData();
  
      formData.append("file", file);
  
      return http.post("/uploadFile", formData, {
        headers: {
          "Content-Type": "multipart/form-data"
        }
      });
    }

Thanks in advance.

**Comment by alijahanpak** [comment]
you can use this code for convert base64 => file : 

``` javascript
 convertBase64ToFile (base64, fileName) {
    const byteString = atob(base64.split(',')[1]);
    const ab = new ArrayBuffer(byteString.length);
    const ia = new Uint8Array(ab);
    for (let i = 0; i < byteString.length; i += 1) {
     ia[i] = byteString.charCodeAt(i);
    }
    const newBlob = new Blob([ab], {
      type: 'image/jpeg',
    });
    return new File([newBlob], fileName)
  },
```

I'll add this feature for next version of handy-uploader
