### ISSUE TITLE
Cannot import sub components

### ISSUE THREAD

**Issue by devonik** [alijahanpak/handy-uploader#8]
Hey, cool library but it's not useable because the sub components can not be found.

I'm using nuxt but I don't think thats the problem

Error

![Unbenannt](https://user-images.githubusercontent.com/16446467/117294443-eff13800-ae72-11eb-9f0f-8ecfabd0147a.png)

**Comment by alijahanpak** [comment]
Thank for create this issue. please use handy-uploader version 1.1.5 to I fix this issue.
npm i handy-uploader@1.1.5
